#!/bin/bash -e

cliName=${0##*/}
authToken="cmVmdGtuOjAxOjE2ODc0NTYxNzk6eVQyS05CNExzeVZKMkZNc3FsN1VLWld6UGMz"




cliHelp(){
    echo "
    This is a CLI for interacting with the Jfrog project Anura
    
    Usage: $cliName [command]
    
    Commands:
        ping        System Ping (/readiness endpoint)
        version     System Version 
        get         Returns info from the Anura project
        createUser  Creates a new user
        help        Help
    "
    exit 1
}

getHelp(){
    echo "
    This is a CLI for interacting with the Jfrog project Anura
    
    Usage: $cliName get [args]
    
    Args:
        key         Generates and returns APIkey
        storage     Returns storage info
        repos       Lists repositories
        help        Help
    "
    exit 1
}


case $1 in 
    ping)
        curl -H "Authorization: Bearer $authToken" https://anura.jfrog.io/artifactory/api/v1/system/readiness
        ;;
    get)
        case $2 in
            key)
                curl -u 'poisondart:Dendrobatidae!1' https://anura.jfrog.io/artifactory/api/security/apiKey
            ;;
            storage)
                curl -H "Authorization: Bearer $authToken" https://anura.jfrog.io/artifactory/api/storageinfo
            ;;
            repos)
                curl -H "Authorization: Bearer $authToken" https://anura.jfrog.io/artifactory/api/repositories
            ;;
            *)
                getHelp
            esac
        ;;
    version)
        curl -H "Authorization: Bearer $authToken" https://anura.jfrog.io/artifactory/api/system/version
        ;;
    createUser)
        curl -v -u 'poisondart:Dendrobatidae!1' -H 'Content-Type:Aplication/scim+json' -XGET https://anura.jfrog.io/artifactory/api/v1/scim/v2/Users
        ;;
    *)
        cliHelp
esac

exit 0

curl -v -u poisondart:cmVmdGtuOjAxOjE2ODc0NTYxNzk6eVQyS05CNExzeVZKMkZNc3FsN1VLWld6UGMz -XGET https://anura.jfrog.io/artifactory

